somelist=['김의찬','유만식','이영철','심수련','윤기석','노윤희','황우철']
print(somelist)
print('앞에서 4번째 요소만 출력')
print(somelist[4])
print('뒤에서 2번째 요소만 출력')
print(somelist[-2])
print('1번째부터 3번째까지 출력')
print(somelist[1:4])
print('4번째부터 끝까지 출력')
print(somelist[4:])
print('짝수 번째만 출력')
print(somelist[0:length:2])
print('3의 배수만 출력')
print(somelist[0:length:3])